### PR TITLE
Master Release

### PR DESCRIPTION
**Pull request by travelist**
- Add API supports for Alert

### CODE REVIEW

**Comment by travelist** [comment]
@marcsolanas @victorfonsec4 @johnugeorge @kazhang 

Reviewable (This is @victorfonsec4's code, thanks!).

BTW, i'm kind of thinking that we actually don't need to get +1 for merging from `develop` to `master` branch since the review was done when it's merged to `develop` branch...?
I can disable the approval requirement for this case if you don't mind.

Anyway, any +1 is helpful.

**Comment by travelist** [comment]
**Update**: Will wait for the alert backend release. Let us know when it's released

**Comment by marcsolanas** [comment]
This merge should ideally be done automatically with a script @kazhang has.

**Comment by travelist** [comment]
@marcsolanas Since it has been long time not to be merged yet, i merged manually this time. Please let me know if there are anythings. 

@victorfonsec4 Thanks for your commits:)

**Pull request merged**
